- menu_name: ""

- name: "Downloads"
  url: "/downloads/"
  title: "Downloads"

- name: "Contacts"
  url: "/contacts/"
  title: "Contacts"

- name: "Imprint"
  url: "/imprint/"
  title: "Legal notice"

- name: "Privacy"
  url: "/privacy/"
  title: "Privacy protection - German"

- name: "Accessibility"
  url: "/accessibility/"
  title: "Legal notice"

- name: "Sitemap"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
